stages:
  - build
  - deploy

build:
  rules:
    - when: manual
  interruptible: true
  image: docker:20.10.7-dind
  stage: build
  services:
    - docker:20.10.7-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY/inigma/app:$CI_COMMIT_SHORT_SHA
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
 
deploy-prod:
  rules:
    - when: manual
  interruptible: true
  stage: deploy
  environment:
    name: prod
    url: https://inigma.idone.su
  image: bitnami/argo-cd:2.7.7
  services:
    - bitnami/argo-cd:2.7.7
  variables:
    PROJECT_NAME: "inigma"
  script:
    - echo ${ARGOCD_SERVER} "," ${PROJECT_NAME} "," ${CI_COMMIT_SHORT_SHA}
    - argocd --server ${ARGOCD_SERVER} --auth-token ${ARGOCD_TOKEN} --grpc-web app set ${PROJECT_NAME} -p image.tag=$CI_COMMIT_SHORT_SHA
    - sleep 10
    - argocd --server ${ARGOCD_SERVER} --auth-token ${ARGOCD_TOKEN} --grpc-web app wait ${PROJECT_NAME} --resource apps:Deployment:$PROJECT_NAME --timeout 300 --health --sync
