stages:
  - build
  - deploy

build-docker:
  interruptible: true
  image: docker:20.10.7-dind
  stage: build
  services:
    - docker:20.10.7-dind
  variables:
    TAG: $CI_COMMIT_REF_NAME-$CI_PIPELINE_IID
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
 
deploy-argocd:
  rules:
    - when: manual
  interruptible: true
  stage: deploy
  image: argoproj/argocd:latest
  services:
    - argoproj/argocd:latest
  variables:
    ARGOCD_VAR: "argovar"
    ARGOCD_VAR2: "aaaaaaaaa"
    ARGOCD_VAR3: "true"
  script:
#    - argocd app set inigma-test -p imageCredentials.username=$CI_REGISTRY_USER --server $ARGOCD_SERVER --auth-token $ARGOCD_TOKEN --grpc-web 
#    - argocd app set inigma-test -p imageCredentials.password=$CI_REGISTRY_PASSWORD --server $ARGOCD_SERVER --auth-token $ARGOCD_TOKEN --grpc-web 
    - argocd app set inigma-test -p imageCredentials.registry=$CI_REGISTRY_IMAGE --server $ARGOCD_SERVER --auth-token $ARGOCD_TOKEN --grpc-web
    - argocd app set inigma-test -p image.tag=latest --server $ARGOCD_SERVER --auth-token $ARGOCD_TOKEN --grpc-web
