version: '3.8'

services:
  inigma:
    build: .
    container_name: inigma-app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - CORS_ORIGINS=https://localhost:8443
    volumes:
      - ./keys:/app/keys
    networks:
      - inigma-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: inigma-nginx
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - inigma
    networks:
      - inigma-network

networks:
  inigma-network:
    driver: bridge