services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - DOMAIN=${CF_DOMAIN}
      - CORS_ORIGINS=https://${CF_DOMAIN}
    networks:
      - inigma-net
    volumes:
      - .:/app
    working_dir: /app
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - app
    networks:
      - inigma-net
    expose:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    depends_on:
      - nginx
    networks:
      - inigma-net
    restart: unless-stopped

networks:
  inigma-net:
    driver: bridge

