version: '3.8'

services:
  inigma:
    build: .
    container_name: inigma
    ports:
      - "8585:8000"
    volumes:
      - ./keys:/app/keys
    environment:
      - DOMAIN=${DOMAIN:-localhost:8585}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
