apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inigma.fullname" . }}
  labels:
    {{- include "inigma.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "inigma.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "inigma.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "inigma.serviceAccountName" . }}
      securityContext:
        {{- .Values.podSecurityContext | toYaml | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- .Values.securityContext | toYaml | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- .Values.env | toYaml | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }} # Updated to use values.yaml
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.containerPort }} # Updated to use values.yaml and TCP
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: {{ .Values.containerPort }} # Updated to use values.yaml and TCP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
