apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "inigma.fullname" . }}
  labels:
    {{- include "inigma.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "inigma.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 8080
          protocol: TCP
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
